version: 2.1
orbs:
  node: circleci/node@4.1.0
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  flights:
    working_directory: ~/project/cloud-functions/flights
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - gcp-cli/install
            - gcp-cli/initialize
            - run: yarn gcloud-deploy

workflows:
  ci:
    jobs:
      - flights
